version: "3"

services:
  contao:
    build:
      context: .
    environment:
      DOCUMENTROOT: "/web"
      DATABASE_URL: mysql://contao-test:contao-test@mariadb:3306/contao-test
      APP_ENV: dev
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    volumes:
      - ./contao-vol/config:/opt/app-root/src/app/config
      - ./contao-vol/files:/opt/app-root/src/files
      - ./contao-vol/templates:/opt/app-root/src/templates
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: contao-password
      MYSQL_DATABASE: contao-test
      MYSQL_USER: contao-test
      MYSQL_PASSWORD: contao-test
    volumes:
      - ./database:/var/lib/mysql
